Repository skni-kod/spacetag, pull requests merged in 2023-02, with the labels that each got.

#6 feat: add orbital element and trajectory visibility toggles
  src/components/satellites-drawer.tsx
  src/components/space/satellite.tsx
  src/components/space/space.tsx
  src/hooks/satellites.ts
Labels: enhancement

#11 docs: update readme authors
  README.md
Labels: documentation

#12 feat: add satellite model
  README.md
  public/assets/models/satellite.obj
  src/components/attribution.tsx
  src/components/space/satellite.tsx
  src/hooks/obj.ts
  src/pages/index.tsx
Labels: enhancement

#13 chore: add `importsNotUsedAsValues` compiler option
  src/components/icons/satellite.tsx
  src/components/space/earth.tsx
  src/components/space/trajectory.tsx
  tsconfig.json
Labels: chore

#14 build: update dependencies
  package.json
  pnpm-lock.yaml
  src/components/space/galaxy.tsx
  src/components/space/sun.tsx
  src/hooks/satellites.ts
  src/hooks/time.ts
  src/pages/index.tsx
Labels: build

#15 chore: replace `@ts-check` with `checkJs`
  .eslintrc.base.js
  .eslintrc.js
  next.config.mjs
  prettier.config.js
  src/environment/client.mjs
  src/environment/schema.mjs
  src/environment/server.mjs
  tailwind.config.js
  tsconfig.json
Labels: chore

#16 chore: update eslint configuration
  .eslintrc.base.js
  .eslintrc.js
  src/components/input.tsx
  src/components/space/satellite.tsx
  src/components/space/trajectory.tsx
  src/components/textarea.tsx
Labels: chore

#17 refactor: simplify environment variables validation
  .eslintrc.js
  next.config.mjs
  src/environment.mjs
  src/environment/client.mjs
  src/environment/schema.mjs
  src/environment/server.mjs
  src/pages/api/trpc/[trpc].ts
Labels: refactoring

#19 fix: reduce satellite label font size
  src/components/space/satellite.tsx
Labels: bug

#20 fix: resolve attribution component hydration error
  src/components/attribution.tsx
  src/trpc/index.ts
Labels: bug

#22 feat: add satellite edit form
  src/components/satellites-drawer.tsx
  src/hooks/satellites.ts
Labels: enhancement

#23 perf: replace `satellite.obj` with `satellite.glb`
  public/assets/models/satellite.glb
  public/assets/models/satellite.obj
  src/components/space/satellite.tsx
Labels: performance

#24 perf: remove react aria
  documentation/pl/skni-kod-website-project-description.md
  package.json
  pnpm-lock.yaml
  src/components/date-drawer.tsx
  src/components/date/field.tsx
  src/components/meter.tsx
  src/components/progress.tsx
  src/pages/_app.tsx
Labels: performance
