Repository skni-kod/spacetag, pull requests merged in 2023-03, with the labels that each got.

#21 feat: add a satellite list
  .eslintrc.js
  .gitignore
  .prettierignore
  package.json
  pnpm-lock.yaml
  scripts/satellites.ts
  scripts/vscode.ts
  src/components/button.tsx
  src/components/combobox.tsx
  src/components/date-drawer.tsx
  src/components/drawer.tsx
  src/components/icons/manage-history.tsx
  src/components/icons/satellite.tsx
  src/components/input.tsx
  src/components/link.tsx
  src/components/menu-drawer.tsx
  src/components/menu.tsx
  src/components/menu/index.ts
  src/components/menu/item.tsx
  src/components/menu/menu.tsx
  src/components/satellites-drawer.tsx
  src/components/space/satellite.tsx
  src/components/space/trajectory.tsx
  src/components/textarea.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/satellite/constants.ts
  src/satellite/types.ts
  src/satellite/utilities.ts
  src/server/router/index.ts
  src/server/router/satellite.ts
  src/types/index.ts
  src/utilities/get-coordinates-from-tle.ts
  tailwind.config.js
Labels: enhancement

#9 feat: add homepage
  next.config.mjs
  src/components/button-link.tsx
  src/components/button.tsx
  src/components/navbar.tsx
  src/pages/app/index.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: enhancement

#25 build: update dependencies
  package.json
  pnpm-lock.yaml
Labels: build

#26 chore: update eslint configuration
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  src/satellite/types.ts
  tsconfig.json
Labels: chore

#27 refactor: fix inconsistencies across the codebase
  src/components/button-link.tsx
  src/components/button.tsx
  src/components/combobox.tsx
  src/components/icons/manage-history.tsx
  src/components/icons/satellite.tsx
  src/components/input.tsx
  src/components/link.tsx
  src/components/menu-drawer.tsx
  src/components/textarea.tsx
  src/pages/app/index.tsx
Labels: refactoring

#28 refactor: replace satellite list buttons with menus
  src/components/menu/menu.tsx
  src/components/satellites-drawer.tsx
Labels: refactoring

#29 feat: add homepage features section
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/assets/images/twinkle.png
  src/components/balancer.tsx
  src/components/fonts.tsx
  src/components/image.tsx
  src/constants/images.ts
  src/pages/_document.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: enhancement

#30 build: update `pnpm-lock.yaml`
  pnpm-lock.yaml
Labels: build

#31 refactor: update meta tags
  public/robots.txt
  src/pages/_document.tsx
  src/pages/app/index.tsx
  src/pages/index.tsx
Labels: refactoring

#32 fix: resolve hydration error in production
  src/pages/index.tsx
Labels: bug

#33 fix: align timeline circles and lines horizontally
  src/pages/index.tsx
Labels: bug
